version: '3.4'

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    volumes:
      - "./init/selenoid:/etc/selenoid"
      - "./work/selenoid/video:/opt/selenoid/video"
      - "./work/selenoid/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=work/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
  selenoid-ui:
    image: aerokube/selenoid-ui
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "8083:8080"
    command: ["--selenoid-uri","http://selenoid:4444"]